# Generated by Django 2.2.17 on 2021-01-30 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Random_Int',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Random_Int_Sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='floor')),
                ('ceiling', models.IntegerField(verbose_name='ceiling')),
                ('generated_at', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.DeleteModel(
            name='Generated_Value',
        ),
        migrations.AddField(
            model_name='random_int',
            name='sequence_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generators.Random_Int_Sequence'),
        ),
    ]
