# Generated by Django 3.1.5 on 2021-01-30 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0002_auto_20210130_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandPwdSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(verbose_name='length')),
                ('pwd_length', models.IntegerField(verbose_name='pwd_length')),
                ('generated_at', models.DateTimeField(verbose_name='generated_at')),
            ],
        ),
        migrations.CreateModel(
            name='RandPwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=128, verbose_name='value')),
                ('set_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generators.randpwdset')),
            ],
        ),
    ]
