# Generated by Django 3.1.5 on 2021-05-30 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0003_make_user_blank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randwordset',
            name='word_length',
        ),
    ]
