# Generated by Django 3.1.5 on 2021-01-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0003_add_pwd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Random_Int',
            new_name='RandInt',
        ),
        migrations.AddField(
            model_name='random_int_sequence',
            name='length',
            field=models.IntegerField(default=1, verbose_name='length'),
            preserve_default=False,
        ),
    ]
