# Generated by Django 3.1.5 on 2021-01-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0004_rename_random_integer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Random_Int_Sequence',
            new_name='RandIntSet',
        ),
    ]
