# Generated by Django 3.1.5 on 2021-01-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generators', '0005_rename_random_integer_set'),
    ]

    operations = [
        migrations.RenameField(
            model_name='randint',
            old_name='sequence_id',
            new_name='set_id',
        ),
    ]
